name: Frontend Continuous Deployment

on:
  push:
    branches:
    - main
    paths:
    - "starter/frontend/**"
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.14]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"
        cache-dependency-path: starter/frontend/package-lock.json
    - name: Install dependencies
      run: npm install
      working-directory: ./starter/frontend
    - name: Lint
      run: npm run lint
      working-directory: ./starter/frontend

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.14]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Install dependencies
      run: npm install
      working-directory: ./starter/frontend

    - name: Test
      run: npm test
      working-directory: ./starter/frontend

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
        aws-region: us-east-1

    - name: Login to Amazon
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image
      working-directory: starter/frontend
      env:
        IMAGE_TAG: ${{ github.sha }}
        REPO_URI: ${{ vars.FRONTEND_ECR_URI }}
        REACT_APP_MOVIE_API_URL: ${{ vars.REACT_APP_MOVIE_API_URL }}

      run: |
        docker build --build-arg=REACT_APP_MOVIE_API_URL=$REACT_APP_MOVIE_API_URL --tag $REPO_URI:$IMAGE_TAG .
        docker push $REPO_URI:$IMAGE_TAG

    - name: Configure Kubeconfig
      env:
        EKS_NAME: ${{ vars.FRONTEND_EKS_NAME }}
      run: aws eks update-kubeconfig --name $EKS_NAME --region us-east-1

    - name: Deploy Docker Image to Amazon EKS
      working-directory: starter/frontend/k8s
      env:
        IMAGE_TAG: ${{ github.sha }}
        REPO_URI: ${{ vars.FRONTEND_ECR_URI }}
      run: |
        kustomize edit set image frontend=$REPO_URI:$IMAGE_TAG
        kustomize build | kubectl apply -f -
